In [1]:
import pandas as pd

In [102]:
item = pd.read_csv("/Users/trba/Documents/Projects/Serbia_housing/nekretnine_rs_raw.csv")

In [103]:
item.head()

,url,title,price_total,price_per_m2,Tip nekretnine,Kvadratura,Broj soba,Oglašivač,Tip objekta,Stanje objekta,...,Klima,Video nadzor,Topla voda,Internet,Parking,Garaža,Lift,Podrum,Linije gradskog prevoza,Dodatni opis
0,https://www.nekretnine.rs/stambeni-objekti/sta...,"Stari grad, Dorćol, Strahinjića Bana, 3.0, 65m...",319 000 EUR\n4 908 €/m²,4 908 €/m²,Trosoban stan,65 m²,3,NaN,NaN,Izvorno stanje,...,da,NaN,NaN,NaN,NaN,NaN,da,NaN,NaN,"Agencijski ID: 94045, III/VI, klima, lift, sal..."
1,https://www.nekretnine.rs/stambeni-objekti/sta...,"Vracar, Metohijska, 88m2, uknjizen, u odlicnom...",308 000 EUR\n3 500 €/m²,3 500 €/m²,Trosoban stan,88 m²,3,NaN,NaN,Izvorno stanje,...,NaN,NaN,NaN,NaN,da,NaN,da,da,NaN,Na prodaju odlican trosoban stan (lako adaptib...
2,https://www.nekretnine.rs/stambeni-objekti/sta...,"Rakovica, Petlovo brdo, Dobrivoja Petkovića, 2...",160 000 EUR\n2 388 €/m²,2 388 €/m²,Dvosoban stan,67 m²,2,NaN,NaN,Izvorno stanje,...,da,NaN,NaN,NaN,da,NaN,NaN,NaN,NaN,"Agencijski ID: 125109, II/IV, klima, uknjižen,..."
3,https://www.nekretnine.rs/stambeni-objekti/sta...,"Izuzetna novogradnja kod TC BIG 110m2, komfora...",266 000 EUR\n2 418 €/m²,2 418 €/m²,Četvorosoban stan,110 m²,4,NaN,NaN,Lux,...,NaN,NaN,NaN,da,da,NaN,da,NaN,NaN,Objekat ima upotrebnu dozvolu i zgrada je uknj...
4,https://www.nekretnine.rs/stambeni-objekti/sta...,Vanvremenski salonac sa baštom i garažom – src...,448 000 EUR\n4 480 €/m²,4 480 €/m²,Četvorosoban stan,100 m²,4,NaN,NaN,Kompletna rekonstrukcija,...,da,NaN,NaN,da,NaN,da,NaN,da,NaN,U ponudi je jedinstven salonski stan u repreze...

In [104]:
#Ovo je sredjivanje titla

item["title"] = item["title"].str.replace(r"\d+|EUR|€/m²|€|m²|m2|\.", "", regex=True).str.strip()
item["title"] = item['title'].str.replace(r", ,","",regex = True).str.strip()
item["title"] = item['title'].str.strip(",")
item['title'].head()

0                Stari grad, Dorćol, Strahinjića Bana
1    Vracar, Metohijska uknjizen, u odlicnom stanju...
2         Rakovica, Petlovo brdo, Dobrivoja Petkovića
3    Izuzetna novogradnja kod TC BIG , komforan  du...
4    Vanvremenski salonac sa baštom i garažom – src...
Name: title, dtype: str

In [105]:
#Zavrseno sredjivanje _price_total
item["price_total"] = (
    item["price_total"]
    .str.split("\n").str[0]
    .str.replace(r"EUR|eur|€|RSD|rsd|DIN|din|Evra|evra|Eura|eura", "", regex=True)
    .str.replace(r"[.,\s]", "", regex=True)
    .str.replace(r"od ", "", regex=True)
    .str.strip()
    .astype("Int64")
)

In [106]:
item['price_total'].head()

0    319000
1    308000
2    160000
3    266000
4    448000
Name: price_total, dtype: Int64

In [107]:
#Zavrseno sredjivanje _price_total
item["price_per_m2"] = (
    item["price_per_m2"]
    .str.split("\n").str[0]
    .str.replace(r"EUR|€/m²|€|m²|m2|\.", "", regex=True).str.strip()
    .str.replace(r"[.,\s]", "", regex=True)
    .str.replace(r"od ", "", regex=True)
    .str.strip()
    .astype("Int64")
)

In [108]:
item["price_per_m2"].head()

0    4908
1    3500
2    2388
3    2418
4    4480
Name: price_per_m2, dtype: Int64

In [109]:
item.head()

,url,title,price_total,price_per_m2,Tip nekretnine,Kvadratura,Broj soba,Oglašivač,Tip objekta,Stanje objekta,...,Klima,Video nadzor,Topla voda,Internet,Parking,Garaža,Lift,Podrum,Linije gradskog prevoza,Dodatni opis
0,https://www.nekretnine.rs/stambeni-objekti/sta...,"Stari grad, Dorćol, Strahinjića Bana",319000,4908,Trosoban stan,65 m²,3,NaN,NaN,Izvorno stanje,...,da,NaN,NaN,NaN,NaN,NaN,da,NaN,NaN,"Agencijski ID: 94045, III/VI, klima, lift, sal..."
1,https://www.nekretnine.rs/stambeni-objekti/sta...,"Vracar, Metohijska uknjizen, u odlicnom stanju...",308000,3500,Trosoban stan,88 m²,3,NaN,NaN,Izvorno stanje,...,NaN,NaN,NaN,NaN,da,NaN,da,da,NaN,Na prodaju odlican trosoban stan (lako adaptib...
2,https://www.nekretnine.rs/stambeni-objekti/sta...,"Rakovica, Petlovo brdo, Dobrivoja Petkovića",160000,2388,Dvosoban stan,67 m²,2,NaN,NaN,Izvorno stanje,...,da,NaN,NaN,NaN,da,NaN,NaN,NaN,NaN,"Agencijski ID: 125109, II/IV, klima, uknjižen,..."
3,https://www.nekretnine.rs/stambeni-objekti/sta...,"Izuzetna novogradnja kod TC BIG , komforan du...",266000,2418,Četvorosoban stan,110 m²,4,NaN,NaN,Lux,...,NaN,NaN,NaN,da,da,NaN,da,NaN,NaN,Objekat ima upotrebnu dozvolu i zgrada je uknj...
4,https://www.nekretnine.rs/stambeni-objekti/sta...,Vanvremenski salonac sa baštom i garažom – src...,448000,4480,Četvorosoban stan,100 m²,4,NaN,NaN,Kompletna rekonstrukcija,...,da,NaN,NaN,da,NaN,da,NaN,da,NaN,U ponudi je jedinstven salonski stan u repreze...